### PR TITLE
Polish Icons

### PR DESCRIPTION
**Pull request by BeckerWdf**
- remove unused sample.png file
- structure icons in icons folder according to eclipse guidline
- new designed icon for abapgit view (including high resolution
  version) and for abapgit wizard banner
- add "original" SVG files that are used to create PNGs. As they
  are not needed during runtime they are not included into the
  JAR file

### CODE REVIEW

**Comment by BeckerWdf** [comment]
@absap: I designed a new icon for the abapgit view and the wizard banner. This change as merge-conflicts. Can you resolve them for me?

**Comment by BeckerWdf** [comment]
Merge conflicts are resolved.

**Comment by absap** [comment]
@larshp what do you think of the new design?

**Comment by larshp** [comment]
👍 LGTM

**Pull request merged**
